### PR TITLE
add note about recompilation gottcha

### PR DESCRIPTION
**Pull request by stephenmoloney**

### CODE REVIEW

**Comment by stephenmoloney** [comment]
Maybe just hold on for a bit with this pull request... checking something....

**Comment by stephenmoloney** [comment]
Ah, ya, I checked and it seems to require a forced recompilation of the dependency or a clean followed by a compile of the dependency

**Comment by doomspork** [comment]
Let's see about changing the code to avoid the need for recompilation 👍

**Comment by stephenmoloney** [comment]
close in favour of #6

**Pull request closed without merging**
