### PR TITLE
Avoid unnecessary compilation

### PR DESCRIPTION
**Pull request by doomspork**
@stephenmoloney take a peek at these changes.

Closes #4 and #5

### CODE REVIEW

**Comment by stephenmoloney** [comment]
@doomspork 
Changing to functions. This will do the trick. I do wonder if there is any difference in terms of performance -- it might well be none but not sure... eitherway, I still think this is better than a forced recompilation of a dependency which is probably not being expected.

:+1: 

Thanks

**Comment by doomspork** [comment]
I was once informed that `Application.get_env` is an ETS lookup and as such is super fast, but I just threw together a quick benchmark and here are the results:

```shell
## ConfigBench
benchmark name       iterations   average time
module attribute         100000   26.88 µs/op
Application.get_env       10000   272.75 µs/op
```

**Comment by stephenmoloney** [comment]
@doomspork 
Yea, that's still quite fast really.

**Comment by doomspork** [comment]
Indeed!  I will merge and cut a release later today when I get back home @stephenmoloney 👍

**Pull request merged**
